name: traefik-real-ip

services:
  whoami:
    image: docker.io/traefik/whoami:v1.11.0@sha256:200689790a0a0ea48ca45992e0450bc26ccab5307375b41c84dfc4f2475937ab
    container_name: traefik-real-ip_whoami
    depends_on:
      traefik:
        condition: service_healthy
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.http.services.traefik-real-ip_whoami.loadbalancer.server.port=80"
      - "traefik.http.services.traefik-real-ip_whoami.loadbalancer.server.scheme=http"
      - "traefik.http.services.traefik-real-ip_whoami.loadbalancer.passhostheader=true"

      - "traefik.http.routers.traefik-real-ip_whoami.service=traefik-real-ip_whoami"
      - "traefik.http.routers.traefik-real-ip_whoami.middlewares=standard@file"
      - "traefik.http.routers.traefik-real-ip_whoami.rule=Method(`GET`)"
      - "traefik.http.routers.traefik-real-ip_whoami.entrypoints=web"

      - "traefik.enable=true"
      - "traefik-real-ip.enable=true"

  traefik:
    image: docker.io/traefik:v3.3.5@sha256:104204dadedf5d1284f8ef8f97f705649ac81aa6f7a6c9abf13e2c59245b8abc
    container_name: traefik-real-ip_traefik
    networks:
      - proxy
      - default
    ports:
      - "4008:80"
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./config:/etc/traefik/mconfig
      - ../:/plugins-local/src/github.com/zekihan/traefik-real-ip:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD-SHELL", "traefik healthcheck | grep OK"]
      interval: 1s
      timeout: 3s
      retries: 5

networks:
  proxy:
    internal: true
  default:
