name: traefik-real-ip

services:
  whoami:
    image: docker.io/traefik/whoami:v1.11.0@sha256:200689790a0a0ea48ca45992e0450bc26ccab5307375b41c84dfc4f2475937ab
    container_name: traefik-real-ip_whoami
    depends_on:
      - traefik
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.services.whoami.loadbalancer.server.scheme=http"
      - "traefik.http.services.whoami.loadbalancer.passhostheader=true"

      - "traefik.http.routers.whoami.service=whoami"
      - "traefik.http.routers.whoami.middlewares=traefik-real-ip@file"
      - "traefik.http.routers.whoami.rule=Method(`GET`)"
      - "traefik.http.routers.whoami.entrypoints=web"

      - "traefik.enable=true"

  traefik:
    image: docker.io/traefik:v3.3.4@sha256:cc11989f418e2cfe5e60fc40c92c1813be847f58eda15eced7d5ac890255ad9e
    container_name: traefik-real-ip_traefik
    networks:
      - proxy
      - default
    ports:
      - "4008:80"
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./config:/etc/traefik/mconfig
      - ../:/plugins-local/src/github.com/zekihan/traefik-real-ip:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  proxy:
    internal: true
  default:
