[global]
    checkNewVersion = false
    sendAnonymousUsage = false

[entryPoints]
    [entryPoints.web]
        address = ":80"

[providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false
    network = "traefik-real-ip_proxy"
    watch = true

[traefikLog]
    filePath = "/var/logs/traefik/traefik.log"
    format   = "json"

[log]
    level = "DEBUG"
    format = "common"

[accessLog]
    bufferingSize = 0
    format = "common"
    [accessLog.filters]
        statusCodes = ["100-800"]
        retryAttempts = true
        minDuration = "0ms"

    [accessLog.fields]
        defaultMode = "keep"

[providers.file]
    directory="/etc/traefik/mconfig/"
    watch="true"

[experimental.localPlugins.traefik-real-ip]
    moduleName = "github.com/zekihan/traefik-real-ip"
