name: Release

on:
  push:
    tags:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

env:
  GOPRIVATE_GITHUB_TOKEN: ${{ secrets.GOPRIVATE_GITHUB_TOKEN }}
  GOPRIVATE: "github.com/zekihan/*"

jobs:
  release:
    runs-on: zekihan.traefik-real-ip
    steps:
      - name: Check Out The Repo
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6.0.0
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Set up GoReleaser
        uses: goreleaser/goreleaser-action@v6.4.0
        with:
          install-only: true

      - name: Install build dependencies
        run: |
          sudo apt-get update -qq
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends make build-essential
          if [ -f .github/scripts/install_build_deps.sh ]; then
            echo "Installing build dependencies from .github/scripts/install_build_deps.sh"
            bash .github/scripts/install_build_deps.sh
          else
            echo "No build dependencies script found, skipping."
          fi

      - name: Configure git for private modules
        env:
          GOPRIVATE_GITHUB_TOKEN: ${{ secrets.GOPRIVATE_GITHUB_TOKEN }}
        run: git config --global url."https://user:${GOPRIVATE_GITHUB_TOKEN}@github.com".insteadOf "https://github.com"

      - name: Make build
        run: |
          make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
